name: flutter_dribbble_ui
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  flutter_chat_bubble: ^2.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner:
  flutter_gen_runner:
  
flutter:

  uses-material-design: true

  assets:
    - assets/pet_adoption/images/
    - assets/e_commerce/images/
    - assets/food_delivery/images/
    - assets/meet_app/images/
    - assets/music_ui/images/
  #   - images/a_dot_ham.jpeg